- stat: path=/usr/local/bin/confd
  register: confd

- name: Install consul
  unarchive:
    src: https://releases.hashicorp.com/consul/1.0.0/consul_1.0.0_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
  when: not confd.stat.exists
